version: '3'

services:
  database:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fterceiraidade_backend_go
    volumes:
      - postgres:/bitnami/postgresql

volumes:
  postgres: