### 
GET http://localhost:8888/
      
###  
GET http://localhost:8888/courses
   
### 
GET http://localhost:8888/courses/b17d9cf7-1618-4237-9dad-7517a8a3839d
  
###  
POST http://localhost:8888/courses
Content-Type: application/json
  
 {
   "name": "course A",
   "description": "course A Full Advanced",
   "image": "/assets/images/blank.png"
 }
 
 
###  
PUT http://localhost:8888/courses/98773285-eec0-45b1-88f4-9018abdb1cbd
Content-Type: application/json
 
 {
   "name": "course A",
   "description": "course A Full Advanced",
   "image": "/assets/images/blank.png"
 }
  
### DELETE
DELETE http://localhost:8888/courses/76b6ccef-3a3f-4a31-b302-21b01c286e12


//-------------------------

      
###       
GET http://localhost:8888/teachers
   
###    
GET http://localhost:8888/teachers/f0a97586-4113-4252-8493-fb2528141cc7
  
###   
POST http://localhost:8888/teachers
Content-Type: application/json
  
{
  "avatar": "/avatar/blank.png",
  "firstname": "Alice",
	"lastname": "Brown",
	"email": "alice@email.com",
	"phone": "+557312345678",
	"address": {
	  "city": "City", 
	  "state": "State", 
    "street": "Street"
  }      
}   
     
//1acbb0ad-e900-44fa-81da-4e03f76dc77d     
###  ec140b6f-966e-4357-bc35-2abc4ebaa17d   
PUT http://localhost:8888/teachers/1acbb0ad-e900-44fa-81da-4e03f76dc77d
Content-Type: application/json
 
 {
  "avatar": "/avatar/blank.png",
  "firstname": "Alice",
	"lastname": "Brown",
	"email": "alice@email.com",
	"phone": "+557312345678",
	"address": {
	  "city": "city", 
	  "state": "state", 
    "street": "street"
  }
}
  
### DELETE
DELETE http://localhost:8888/teachers/75ac96ea-b117-40fd-9b84-ccfd4605454c

//-------------------------
       
###   
GET http://localhost:8888/students
   
### 
GET http://localhost:8888/students/fe79e05c-6180-4bb8-98c5-2b9d1d3aef10
  
### 
POST http://localhost:8888/students
Content-Type: application/json
  
{
  "avatar": "/avatar/blank.png",
  "firstname": "Rebecca",
	"lastname": "Green",
	"email": "rebecca1@email.com",
	"phone": "+5512345678",
	"address": {
	  "city": "city", 
	  "state": "state", 
    "street": "street"
  }
} 
     
###  
PUT http://localhost:8888/students/fe79e05c-6180-4bb8-98c5-2b9d1d3aef10
Content-Type: application/json
 
 {
  "avatar": "/avatar/blank.png",
  "firstname": "Rebecca",
	"lastname": "Green",
	"email": "rebecca3@email.com",
	"phone": "+557312345678",
	"address": {
	  "city": "City", 
	  "state": "state", 
    "street": "Street"
  }
} 
  
### DELETE
DELETE http://localhost:8888/students/046e675f-4b77-4c1a-a081-278e13c1e9ed

//-------------------------
       
### 
GET http://localhost:8888/questions
   
### 
GET http://localhost:8888/questions/0def932d-01fa-4e8c-be1b-b4694b6fc115
  
### 
POST http://localhost:8888/questions
Content-Type: application/json
  
{
  "questioning": "Pergunta específica sobre",
	"type": "objetiva",
  "image": "/avatar/blank.png",
	"alternatives": ["(a) alternativa a", "(b) alternativa b", "(c) alternativa c"],
	"answer": "Resposta sobre a pergunta específica",
	"discipline": "Lógica de programação"
}

### 
PUT http://localhost:8888/questions/0def932d-01fa-4e8c-be1b-b4694b6fc115
Content-Type: application/json
 
{
  "questioning": "Pergunta específica sobre",
	"type": "objetiva",
  "image": "",
	"alternatives": [
		"(a) alternativa a",
		"(b) alternativa b",
		"(c) alternativa c"
	],
	"answer": "",
	"discipline": "Lógica de programação"
}
  
### DELETE
DELETE http://localhost:8888/questions/046e675f-4b77-4c1a-a081-278e13c1e9ed

//-------------------------
       
###  
GET http://localhost:8888/classrooms
    
### 
GET http://localhost:8888/classrooms/1d6b485a-efca-4e5d-af0e-7c769a0d6874
  
### 
POST http://localhost:8888/classrooms
Content-Type: application/json
   
{
  "name": "Classroom A",
  "description": "Classroom A Full Advanced",
  "course": "98773285-eec0-45b1-88f4-9018abdb1cbd"
}

### 
PUT http://localhost:8888/classrooms/1d6b485a-efca-4e5d-af0e-7c769a0d6874
Content-Type: application/json
 
{
  "name": "Classroom A",
  "description": "Classroom A Full Advanced",
  "course": "b17d9cf7-1618-4237-9dad-7517a8a3839d"
}
  
### DELETE
DELETE http://localhost:8888/classrooms/0d6b485a-efca-4e5d-af0e-7c769a0d6874
	
//-------------------------
        
###   
GET http://localhost:8888/assessments
        
###   
GET http://localhost:8888/assessments/b34750a4-072d-412b-89d3-8251b777d6c2
      
### 
POST http://localhost:8888/assessments
Content-Type: application/json

{
	"description": "Assessment description",
	"courses": ["98773285-eec0-45b1-88f4-9018abdb1cbd"],
	"classrooms": ["27986656-fd2a-4c87-9f67-33dba2ff8b10"],
	"start_date": "2024-03-18",
	"end_date": "2024-03-19",
	"quiz": [
		{
			"ID": "1d6b485a-efca-4e5d-af0e-7c769a0d6874",
			"value": 14
		},
		{
			"ID": "b17d9cf7-1618-4237-9dad-7517a8a3839d",
			"value": 71
		}
	]
}  
    
###   
PUT http://localhost:8888/assessments/2eaab477-6e77-4f19-90fa-b5e30e43af11
Content-Type: application/json
 
{
	"description": "Assessment description",
	"courses": ["98773285-eec0-45b1-88f4-9018abdb1cbd", "98773285-eec0-45b1-88f4-9018abdb1cbd"],
	"classrooms": ["27986656-fd2a-4c87-9f67-33dba2ff8b10"],
	"start_date": "2024-01-29",
	"end_date": "2024-02-03",
	"quiz": [
		{
			"ID": "1d6b485a-efca-4e5d-af0e-7c769a0d6874",
			"value": 14
		},
		{
			"ID": "b17d9cf7-1618-4237-9dad-7517a8a3839d",
			"value": 71
		}
	]
}
 
### DELETE
DELETE http://localhost:8888/assessments/857cbabb-4035-43aa-8324-d924a0124b07
